### ISSUE TITLE
Check manager status takes very long

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#25] opened 2018-08-20 04:03 UTC
The check manager status task is taking about 20 minutes After the manager itself is deployed.
Perhaps too much sleep time?

**Comment by kais66** [comment] 2018-08-20 21:43
We suspect the manager deployment itself takes a long time because much needs to be done: upload a ~3.6GB .ova, configure, spin it up.

In other words, the problem is that it takes a long time, it's not a problem with Ansible.

The module nsxt_manager_status  doesn't do anything other than polling the NSX manager about its deployment status.

**Comment by kais66** [comment] 2018-08-31 17:09
This behavior has been observed consistently. Closing the issue.

**Closed as completed by kais66** 2018-08-31 17:09 UTC
